### ISSUE TITLE
Extension preferences

### ISSUE THREAD

**Issue by aunetx** [PRATAP-KUMAR/Control_Blur_Effect_On_Lock_Screen#1]
Hello, first of all, thanks for this extension!

It works great, but the only thing missing is obviously the ability to manage opacity from settings easily.
Would you like me to do a pull request to add preferences?

**Comment by PRATAP-KUMAR** [comment]
I would like to know “easily" do you mean avoiding dconf?

yes please goahead with preferences..

**Comment by aunetx** [comment]
Yes: you have the ability to use a Gtk widget to change dconf settings with the extension itself.
You know, those are the preferences that are available when installing an extension.

I will make a pull request whenever I can

**Comment by aunetx** [comment]
I made the pull request #2

**Comment by PRATAP-KUMAR** [comment]
I will go through it..

**Comment by aunetx** [comment]
Thanks, don't hesitate to ask me questions about it

**Comment by PRATAP-KUMAR** [comment]
Hi, I have gone through it.. Excellent Job!!!

**Comment by aunetx** [comment]
Tanks a lot!
By the way, you can remove the dconf-related instructions from the README (as it is not needed any more) :)

**Comment by PRATAP-KUMAR** [comment]
Yups.. While I was doing that you posted this msg.. Readme is updated as well. I really appriciate your time on this and I guess you are the perfect coder.. while I am just a Ubuntu user without any computer background!

**Comment by PRATAP-KUMAR** [comment]
I will upload the latest version of this (your PR) to gnome-extensions tomorrow morning or say in 10hrs.. Its 10:40PM now..

**Comment by aunetx** [comment]
Hehe thanks a lot but believe me, I was in the same case as yours 2 weeks ago with my own extension, so adding preferences to your extension was very similar actually ^^
And in my own extension, it took me 1 week so I'm not at all the perfect coder sadly :)

Good chance for later!

**Comment by PRATAP-KUMAR** [comment]
great!.. but I Will call you as a perfect coder.. plz share the link of the extension you mentioned..

**Comment by aunetx** [comment]
That's an honour to be called like that ^^
[This is my extension](https://extensions.gnome.org/extension/2588/fully-transparent-top-bar/), hope it will suit you!
