### ISSUE TITLE
Gnome-40.1 not work - to solve this add this

### ISSUE THREAD

**Issue by getro1888** [PRATAP-KUMAR/Control_Blur_Effect_On_Lock_Screen#3]
Arch linux must to be installed manually because you need to change the version from 40.0 to 40 or add version 40, 40.0, 40.1.
i install on arch Gnome-40.1 works. you neet to install it manually.

add the version to 40.0 to -> 40 only

**Comment by PRATAP-KUMAR** [comment]
Done.
