### ISSUE TITLE
breaks lock-screen

### ISSUE THREAD

**Issue by foer** [PRATAP-KUMAR/Control_Blur_Effect_On_Lock_Screen#4]
Hi. One of the last updates in manjaro (eventually gnome-shell or mutter) breaks this extension. Locking the screen doesn't work anymore, the desktop remains visible but there are a lot of problems then. You can control everything around the gnome-shell panel with the mouse, e.g. shutdown, but everything else isn't working, e.g. closing a window or starting a program from the Dash to Dock.

**Comment by PRATAP-KUMAR** [comment]
Hi.. yesterday I came to know about the update in gnome-shell.. will see in a while..

**Comment by PRATAP-KUMAR** [comment]
Hi, I Confirm the issue..
I am trying to rectify/update the extension for gnome-shell > 3.36
probably it takes a day or two to update the extension..
Thanks for reporting...!!!

**Comment by foer** [comment]
Hi,
thank you very much for answering!

```
[foer@foer-manjaro ~]$ gnome-shell --version
GNOME Shell 3.36.4
```

**Comment by PRATAP-KUMAR** [comment]
Hi, I am working on this since morning, I mean almost 4 hrs.. extension works upto 3.36.3 gnome-shell version.. I am not able to install 3.36.4 to test it.. but my workarounds are making clueless.. {{{[[[ can you remove the extension from your system.. reboot.. then lock the system.. what is happening? ]]]}}} in my case even If I remove the extension.. my system is breaking of course it is not official version of gnome 3.36.4

**Comment by PRATAP-KUMAR** [comment]
Hi, trying since morning.. I mean almost 12hrs.. I tried to install 3.36.4 manually and broke the Ubuntu 20.04.. Reinstalled it.. Tried Manjaro iso downloading.. installed.. but cant upgrade to 3.36.4.. so giving up.. do you have any link to iso which uses 3.36.4 out of the box.. I have to wait until I can access to 3.36.4

**Comment by PRATAP-KUMAR** [comment]
https://askubuntu.com/questions/1258607/how-to-update-the-gnome-shell-version-to-the-latest-ubuntu-20-04

**Comment by foer** [comment]
Hi, i have no idea how to get gnome-shell 3.36.4 on ubuntu. On Manjaro you have to switch to the  [testing branch](https://wiki.manjaro.org/index.php?title=Switching_Branches) . Normally a package in testing branch will come to the stable branch a few days or weeks later.

**Comment by PRATAP-KUMAR** [comment]
Ok, I will try now with testing branch switch.. If you remove the extension, reboot and lock the screen.. Is it working, I mean the system..

**Comment by foer** [comment]
> If you remove the extension, reboot and lock the screen.. Is it working, I mean the system..

Yes. Everything is working as intended then...

**Comment by PRATAP-KUMAR** [comment]
Hi just reviewed 3.36.4.. would you like to test it now or will wait until gnome-extension site approves the update?

![Screenshot from 2020-07-13 13-46-43](https://user-images.githubusercontent.com/40719899/87280314-a2849280-c50f-11ea-818e-fc0294942d07.png)

![Screenshot from 2020-07-13 13-47-06](https://user-images.githubusercontent.com/40719899/87280331-a6b0b000-c50f-11ea-868c-a40c62cfbf16.png)

**Comment by foer** [comment]
Hi, thank you very much. 
I can test it now. Should i use the master-branch?

**Comment by PRATAP-KUMAR** [comment]
yes but wait a bit.. I need to update the master branch.. I am ready but power/electricity fluctuations occuring. may be in 20mins power/electricity will be resumed and then I will update the extension.. will you be available after 20min?

**Comment by foer** [comment]
ok...i'm in a meeting the next approx 60 min but afterwards i can have a look at the master branch...

**Comment by PRATAP-KUMAR** [comment]
Hey now the master branch is updated.. you can test it now..
Thank you so much for giving me opportunity to experience about `manjaro` OS

**Comment by foer** [comment]
Hi, the extension is working perfect now! Thank you very much for that extension and your brilliant work!

**Comment by PRATAP-KUMAR** [comment]
will see you on some other update then.. nice meeting you!!!

**Comment by aunetx** [comment]
Wow, quick fix :)

I personally think that it would be better to test for the entire version (because you are just testing the microversion, but when gnome 3.38.1 will be released, the old version will  be used right? Or maybe I did not understand well the fix)

**Comment by PRATAP-KUMAR** [comment]
you are rite.. I will update once 3.38 is out for testing .. the fix is mainly for the OP..

**Comment by PRATAP-KUMAR** [comment]
can you help me for the prefs.js for BringOutPowerOffExtension

**Comment by aunetx** [comment]
Ok super! That is what I was thinking ^^ good job ;)
