### ISSUE TITLE
Extensions prefs fail to open

### ISSUE THREAD

**Issue by pacho2** [PRATAP-KUMAR/Control_Blur_Effect_On_Lock_Screen#5]
When I try to open extensions prefs from gnome-extensions-app it fails with this error with Gnome 40.1
The settings of extension ControlBlurEffectOnLockScreen@pratap.fastmail.fm had an error:
```
Gtk.BuilderError: /usr/share/gnome-shell/extensions/ControlBlurEffectOnLockScreen@pratap.fastmail.fm/prefs.ui:18:36 Invalid property: GtkGrid.border_width
```

Stack trace:
```
_init@/usr/share/gnome-shell/extensions/ControlBlurEffectOnLockScreen@pratap.fastmail.fm/prefs.js:30:17
wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:83:27
buildPrefsWidget@/usr/share/gnome-shell/extensions/ControlBlurEffectOnLockScreen@pratap.fastmail.fm/prefs.js:15:18
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

Thanks

**Comment by PRATAP-KUMAR** [comment]
Hi thanks for reporting this. I have tested the extension just now with gnome-shell --version 40.1 in my Arch Linux. Did not find any problem. I suspect you have installed it from github page. Can you try directly from gnome-extensions website. Shell Version 40 Extension version 10.

![Screenshot](https://user-images.githubusercontent.com/40719899/121486448-c5087f80-c9ee-11eb-828c-9b6834ebc065.png)

**Comment by pacho2** [comment]
I cannot install it from:
https://extensions.gnome.org/extension/2935/control-blur-effect-on-lock-screen/

It is tagged as "incompatible"

**Comment by PRATAP-KUMAR** [comment]
I have just now checked again, and it is working for me.
Can you please provide the out put of
````
cat /etc/os-release
````

and
````
gnome-shell --version
````

**Comment by pacho2** [comment]
# cat os-release 
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"

$ gnome-shell --version
GNOME Shell 40.2

Thanks

**Comment by PRATAP-KUMAR** [comment]
Thanks for the out puts.

I am sorry. Its a mistake from my end.
Can you install with this zip file.

Download it in your systems `Downloads` directory.  
Then run below commands

````
cd Downloads
gnome-extensions install -f ControlBlurEffectOnLockScreen@pratap.fastmail.fm.zip
````
Alt+F2 r enter or logout and login

````
gnome-extensions enable ControlBlurEffectOnLockScreen@pratap.fastmail.fm
````

[ControlBlurEffectOnLockScreen@pratap.fastmail.fm.zip](https://github.com/PRATAP-KUMAR/Control_Blur_Effect_On_Lock_Screen/files/6646603/ControlBlurEffectOnLockScreen%40pratap.fastmail.fm.zip)

**Comment by PRATAP-KUMAR** [comment]
I have updated in https://extensions.gnome.org/ website too. You can Directly download from there. https://extensions.gnome.org/extension/2935/control-blur-effect-on-lock-screen/

![Shell Version 40 Extension Version 11](https://user-images.githubusercontent.com/40719899/121863133-272bf200-cd19-11eb-9162-0dbadfc9eac7.png)

**Comment by pacho2** [comment]
It works fine, thanks :D

Can you please also update it here in github repo? It would be really useful for me as I package the extension for Gentoo, and I am sure other distribution downstream maintainers would also be interested on it

Thanks

**Comment by PRATAP-KUMAR** [comment]
It's "gnome-shell 40" branch in GitHub.

**Comment by pacho2** [comment]
It works perfectly, thanks a lot!

**Comment by pacho2** [comment]
The only "regression" I see is that gnome-shell-40 branch re-enables the "disable" function and, as a consequence, blur settings get lost after resume from suspend. It misses:
https://github.com/PRATAP-KUMAR/Control_Blur_Effect_On_Lock_Screen/commit/748b95e931b6b1548b90ceeee7a5883da3e0529f

**Comment by PRATAP-KUMAR** [comment]
Ok. I have edited `extension.js` file accordingly in github repo. But this change cannot be done in gnome-extensions website.

**Comment by pacho2** [comment]
Fine, will update it downstream

Thanks a lot and best regards

**Comment by pacho2** [comment]
I have seen that doesn't work anymore with this version. On the other hand, the old extension from 'master' (plus manually changing metadata to allow gnome 40) still work.

The problem is that, when waking up from suspend (at least running Xorg + nvidia-drivers), the unblurred background is seen for a fraction of seconds,, but later a blurred one is shown over it.

I have been tried to migrate section by section from old extension (from 'master') to this one, and it seems that the old _controlBlur1 logic is the only one that always works. Even if I drop all the version conditional and force to always run controlBlur1 instead of the newer controlBlur, it works :/

**Comment by PRATAP-KUMAR** [comment]
You did lot of work on this. I Appreciate.
My laptop does not have graphic cards and with out editing the disable function also, It seems to work in my case with Arch Linux.

**Comment by pacho2** [comment]
I think it's a collision between https://github.com/neffo/bing-wallpaper-gnome-extension and this extension, but still unsure about the reason because I have disabled its "blur" handling to not collide with this extension:
https://github.com/neffo/bing-wallpaper-gnome-extension/issues/113

But I think that, in some way, bing extension is now re-loading at some point when resuming and causing the blur to be re-added. It is also weird because the ugly thing happens I close the laptop lid and resume happens but not when running "systemctl suspend" from the terminal...

**Comment by pacho2** [comment]
I found the issue I think:
https://github.com/neffo/bing-wallpaper-gnome-extension/issues/113#issuecomment-860921398

Lets see if we can make both co-exist :)
